version: '3.7'
services:
  jenkins:
    image: "jenkins/jenkins:lts"
    networks:
      - ci_net
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "jenkins:/var/jenkins_home"

  artifactory:
    image: "docker.bintray.io/jfrog/artifactory-oss"
    networks:
      - ci_net
    ports:
      - "8081:8081"
    volumes:
      - "artifactory:/var/opt/jfrog/artifactory"

volumes:
  jenkins:
  artifactory:

networks:
  ci_net:
